"""Make staff_id optional in orders

Revision ID: dcec2e5a6a18
Revises: 122f5288c5cd
Create Date: 2026-01-14 23:09:12.958846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcec2e5a6a18'
down_revision = '122f5288c5cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finances')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('staff_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('staff_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('finances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('payment_id', sa.INTEGER(), nullable=False),
    sa.Column('total_income', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_finances_payment_id_payments')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
